name: comms
description: Simple communication pattern abstraction on streams, created for communication between logic classes.
version: 0.0.4
homepage: https://github.com/leancodepl/comms

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  logging: ^1.0.2
  meta: ^1.7.0
  uuid: ^3.0.6

dev_dependencies:
  leancode_lint: ^1.2.1
  test: ^1.16.4