name: comms
description: Simple communication pattern abstraction on streams, created for communication between logic classes.
version: 1.0.1
homepage: https://github.com/leancodepl/comms

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  logging: ^1.2.0
  meta: ^1.9.1

dev_dependencies:
  leancode_lint: ^4.0.0+1
  test: ^1.17.5
