name: comms
description: Simple communication pattern abstraction on streams, specifically created for bloc to bloc communication.
version: 0.0.3
homepage: https://github.com/leancodepl/comms

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  bloc: ^8.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2
  logging: ^1.0.2
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^1.2.1