name: flutter_comms
description: Simple communication pattern abstraction on streams, created for communication between logic classes and or widgets.
version: 1.1.0
homepage: https://github.com/leancodepl/comms

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  comms: ^1.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  logging: ^1.2.0
  meta: ^1.9.1
  nested: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^6.0.0
