name: flutter_comms
description: Simple communication pattern abstraction on streams, created for communication between blocs and or widgets.
version: 0.0.6+2
homepage: https://github.com/leancodepl/comms

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.0
  comms: ^0.0.9
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2
  logging: ^1.0.2
  meta: ^1.7.0
  nested: ^1.0.0
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^2.1.0+1
