name: flutter_comms
description: Simple communication pattern abstraction on streams, created for communication between blocs and or widgets.
version: 1.0.0
homepage: https://github.com/leancodepl/comms

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0 <4.0.0"

dependencies:
  comms: ^1.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2
  logging: ^1.2.0
  meta: ^1.9.1
  nested: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^4.0.0+1
