name: comms prepare

on:
  push:
    branches: [master]
    tags-ignore: ["comms-v*"]
    paths:
      - "packages/comms/**"
  pull_request:
    branches: [master]
    paths:
      - "packages/comms/**"

jobs:
  main:
    name: Dart ${{ matrix.sdk }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        sdk: [2.16.2, stable, beta]

    defaults:
      run:
        working-directory: packages/comms

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install mobile-tools
        uses: actions/checkout@v3
        with:
          repository: leancodepl/mobile-tools
          path: mobile-tools

      - name: Add mobile-tools to $GITHUB_PATH
        run: |
          sudo apt install tree
          tree
          echo "PWD: $PWD"
          echo "$PWD/mobile-tools/mobile-tools/bin" >> $GITHUB_PATH
          echo "$PWD/mobile-tools/bin" >> $GITHUB_PATH

      - name: Test mobile-tools
        run: |
          link-changelog comms comms-v0.0.5 comms-

      - name: dart pub get
        run: dart pub get

      - name: dart analyze
        run: dart analyze

      - name: dart test
        run: dart test

      - name: dart format
        run: dart format --set-exit-if-changed .
