name: comms publish

on:
  push:
    tags: ["comms-v*"]

jobs:
  main:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    defaults:
      run:
        working-directory: packages/comms

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.0.6

      - name: Install mobile-tools
        uses: actions/checkout@v3
        with:
          repository: leancodepl/mobile-tools
          path: mobile-tools

      - name: Add mobile-tools to PATH
        run: |
          echo $GITHUB_WORKSPACE/mobile-tools/bin >> $GITHUB_PATH

      - name: Set version data
        run: |
          package_name=comms
          tag=${{ github.ref_name }}
          echo "RELEASE_NOTES=$(link-changelog $package_name $tag)" >> $GITHUB_ENV
          echo "IS_PRERELEASE=$(is_prerelease $package_name $tag)" >> $GITHUB_ENV

      - name: Publish
        run: dart pub publish -f

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          body: ${{ env.RELEASE_NOTES }}
          prerelease: ${{ env.IS_PRERELEASE }}
