name: comms prepare

on:
  push:
    branches: [master]
    tags-ignore: ["comms-v*"]
    paths:
      - "packages/comms/**"
  pull_request:
    branches: [master]
    paths:
      - "packages/comms/**"

jobs:
  main:
    name: Dart ${{ matrix.sdk }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        sdk: [2.17.0, 3.0.0]

    defaults:
      run:
        working-directory: packages/comms

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: dart pub get
        run: dart pub get

      - name: dart analyze
        run: dart analyze

      - name: dart test
        run: dart test

      - name: dart format
        run: dart format --set-exit-if-changed .
