name: flutter_comms publish

on:
  push:
    tags: ["flutter_comms-v*"]

jobs:
  main:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: packages/flutter_comms

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.17.0

      - name: Install mobile-tools
        uses: actions/checkout@v3
        with:
          repository: leancodepl/mobile-tools
          path: mobile-tools

      - name: Add mobile-tools to PATH
        run: |
          echo $GITHUB_WORKSPACE/mobile-tools/bin >> $GITHUB_PATH

      - name: Download pub.dev credentials
        env:
          CREDENTIALS: ${{ secrets.PUB_DEV_CREDENTIALS }}
        run: |
          mkdir -p ~/.pub-cache
          echo $CREDENTIALS > ~/.pub-cache/credentials.json

      - name: Set version data
        run: |
          tag=${{ github.ref_name }}
          prefix=flutter_comms-v
          echo "RELEASE_NOTES=$(link-changelog flutter_comms $tag $prefix)" >> $GITHUB_ENV
          # TODO: Remove in the future
          # set whether is prerelease
          version=${tag#"$prefix"}
          is_prerelease=false
          if [[ "$version" == 0.* ]]; then
            is_prerelease=true
          fi
          echo "IS_PRERELEASE=$is_prerelease" >> $GITHUB_ENV

      - name: Publish
        run: dart pub publish -f

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: "flutter_comms-v${{ env.VERSION }}"
          prerelease: ${{ env.IS_PRERELEASE }}
