name: flutter_comms prepare

on:
  push:
    branches: [master]
    tags-ignore: ["flutter_comms-v*"]
    paths:
      - "packages/flutter_comms/**"
  pull_request:
    branches: [master]
    paths:
      - "packages/flutter_comms/**"

jobs:
  main:
    name: Flutter ${{ matrix.channel }}${{ matrix.version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 3.0.0

    defaults:
      run:
        working-directory: packages/flutter_comms

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2.6.2
        with:
          channel: ${{ matrix.channel }}
          flutter-version: ${{ matrix.version }}

      - name: flutter pub get
        run: flutter pub get

      - name: flutter analyze
        run: flutter analyze

      - name: flutter test
        run: flutter test

      - name: flutter format
        run: flutter format --set-exit-if-changed .
